*******NICRAINC
* VAX FORTRAN include statements!
      INCLUDE 'NICRAPAR.FOR/LIST'
*
      COMMON /HAMPAR/EPS,GAM,EPS4,OMEG,NDIM(MSYM,MISO),ISO,
     &NUMBER(MISO),IANT,MOVE,NEUMOV
*
      COMMON /NILSPAR/RKAPPA(15,MISO),RMY(15,MISO),
     & RHOMEGA(MISO),OMOM,NUU,JCO,NMAX(MISO)
*
      COMMON /HAMILTON/EIJ(MAXDIM,MAXDIM,MSYM),RJXIJ(MAXDIM,MAXDIM,MSYM)
     &,Q2IJ(MAXDIM,MAXDIM,MSYM)
*
      COMMON /QUANTA/NVAL(MAXDIM,MSYM),LVAL(MAXDIM,MSYM),
     & JVAL(MAXDIM,MSYM),MVAL(MAXDIM,MSYM)
*
      COMMON /ISOS/ ETOTI(MOMEGA,MISO),SPINI(MOMEGA,MISO),
     & Q2TOTI(MOMEGA,MISO),VAR(MOMEGA),ICONFI(MOMEGA,MISO),
     & EBCS(MOMEGA,MISO),ESHELL(MOMEGA,MISO)
*
      COMMON /SETTINGS/IF_SPOUT,IF_STRUT,LEV_PRINT,IF_LEVSAV,
     &IF_ISOENEROUT,IF_TOTEOUT,MODELTYP,ISYM1,ISYM2,ISO1,ISO2,NVAR,
     &IF_MEV,SPERANGE,IF_Q2,IF_NIVPRI,IF_DROPCALC,IF_BCS,IN_LEV,
     &ISTEP
*
      COMMON /FILES/NSPFILE,NSAV1FIL,NSAV2FIL,NSAV3FIL,NTOTFILE
      COMMON /SAVFIL/IPSAV,ITEST,IBLK,IBLW,IF_SAVDROP
*
      COMMON /ORBITALS/E(MAXD2,MSYM,MOMEGA),RJX(MAXD2,MSYM,MOMEGA),
     &Q2(MAXD2,MSYM,MOMEGA),VEC(MAXDIM,MAXD2,MSYM)
*
      COMMON /STRUTI/ESTRUT(MISO),STRUTINERTIA,ELAM(MISO),
     &DROPENERGY,DROPINERTIA,ESTRU_LAST(MISO),SPIN_STRU(MISO),
     &BCS_EN(MISO),BCS_DEL(MISO),GPAIR(MISO),G0,G1,KOEFF_RANGE
*
      COMMON /LOOPS/IDEF_TYP,FI,NEPS,EPSI(MDEF),NGAM,GAMI(MDEF),
     &NEPS4,EPS4I(MDEF),NOMEGA,OMEGA(MOMEGA),I4,IG,IE,ILOOP,NERR
*
      COMMON /TOTALS/ UT_TOT(MOMEGA),UT_OM(MOMEGA),
     &UT_SPIN(MOMEGA),UT_Q2(MOMEGA),
     &UT_EPS(MOMEGA),UT_GAM(MOMEGA),
     & UT_EP4(MOMEGA),UT_CONF(MOMEGA)
*
      CHARACTER ERR_TEX(MERR)*80
      COMMON/ERR_LOG/ERR_TEX
*
      CHARACTER ANUC(100)*2,ISOTEXT(2)*8,ENT*4
      COMMON /NUC_TEXT/ISOTEXT,ANUC,ENT
