      SUBROUTINE FFCALE
CCCCCC
      PARAMETER(NHS=9,NPS=9,LXA=150,LXB=150,LPH=10,LMM=4,LTL=9)
      PARAMETER(NXA=420,NXB=140,NIN=300,NOU=300,N1X=140)
      PARAMETER(KFM=10,KAA=40,KBB=30,KCC=80,KGG=125,KJL=600,KTEN=5000)
      PARAMETER(LMJ=10,LRP=11,L1X=10,L2X=60,LM1=5,LM2=30,LAB=2000)
CCCCCC
      COMMON/CNST  /FACLOG(500),PI,HBAR,AMAS,WNUNIT,FINE
      COMMON/BSX/   URSAVE(500),ENEPT,VNEPT,VSOR,DFNR,DFNSO,RZR,RZSO,
     1              RZC,XMES2,Q,FTR,NODER,LBTR,JBTRTW,NXRAWF,KTRL4,
     2              KOPOT,LBTRY,JBTWY
      COMMON/DWCC/  LDWMIR(4),LDWMXR(4),WN(4),LDWSTR(4),CE(4),CFUNIR(4),
     1              ECM(4),XMESR(4),NXMXR(4),NXMIR(4),NOEXP,MXSTEP,
     2              TMASA,TMASB,TMASX,TMASY,PMASA,PMASB,PMASX,PMASY,
     3              TZA,TZB,TZX,TZY,
     4              PZA,PZB,PZX,PZY,XBARD(4),XBARID(4),WNXD(20),EXPD(20)
      COMMON/CNTRL/ KTRLD(9),KTLOUT(24),NERUN,KRTYPE
      COMMON/FFCC/  VRANG(6),VSTR(12,6),VV(300,24),XMESH,XMESC,
     1              XMESHD,XMESHE,RHED(300),
     2              NBCMI,NBCMX,NONB,NBSTEP,LASTEP,LBSTEP,MAMAX,MXMAX,
     3              MP1MAX,NOLA,NOLB,INTRAN,LMI,LMX,KCETN(2),
     4              NCMAX,NCMIN,LDMAX,JATRTY,NONA,NONAH,NONAR,NASTEP,
     5              NHDMX,NHEMX,NGAUSR,NBSTPD,NBSTPE,N1STEP,JATW,ISATW
      COMMON/CNORE/ FACNR,LRP1MX
      COMMON/CDENS/ RHOE(NXA,NIN,LMM),USAVEX(4*NXA),SPEC(4),
     1              DENSTY(NXA),LAMMXD(3),LBXD(4),NOSTX,NDMY
      COMMON/SPSTAT/EET,SPECTA(LPH),ESP(LPH),ESH(LPH),NSP(LPH),LSP(LPH),
     1              JTWP(LPH),NSH(LPH),LSH(LPH),JTWH(LPH),IPAIR,NOSP,
     2              NOSH,NPST(LPH),NHST(LPH),NPAIRD,L1R(8),ISR(8),
     3              ITR(8),NLSMAX,JT,KPARIT,IST,NOLTR,N1,LTR(8),
     4              ITP(LPH),ITH(LPH),ITZP(LPH),ITZH(LPH)
      COMMON/CCKF/  L1KFD(KFM),ISKFD(KFM),KKFD(KFM),LTKFD(KFM),KFMAX,
     1              ITKFD(KFM),NLSKFD(KFM),NLTKFD(KFM),LTMIM,LTMAX
      COMMON/SPECFC/ALPHA(30,6)
      COMMON/CGFAC /KAMAX,KGMAX,KCMAX,JLSMX,KBBSD(10),
     1              KBC(KCC),LAM2PC(KCC),LPP1C(KCC),LLP1D(KCC),
     2              NINTC(KCC),KDD(KGG),KCD(KGG),NLSD(KGG),LAMD(KAA),
     3              CLEBQ(KCC,5),CLEBF(KAA,5,5),COEF(KGG),CDDD(KJL) 
      COMMON/CGFAC2/JLSPMX,JLSCMX,KAD(KGG,5),NLTD(KJL),KKD(KJL),
     1              LAD(KJL),LBD(KJL),LYD(KJL),LTD(KJL),NND(KJL),
     2              CLEBD(KJL,10),CCDD(KJL,10) 
      COMMON/CGGR/  GGRIE(L1X,N1X)
      COMPLEX       GGRIE
      COMMON/CGAUS/ NGAUS,NONE1,RTS(96),WGT(96),RA,RB,GKINT(20),
     1              GFT(200),VBS(120),VBE(120)
      COMMON/DISW / DISWB(LXB*NXB),DISWA(LXA*NXA)
      COMPLEX       DISWA,DISWB
      COMMON/TREDEN/GWT(N1X,NIN,LM2),TRHO(N1X,NIN,KBB)
      DIMENSION     P(130,30),PP(130,10)
      DIMENSION     AF(500),AFI(500),XAF(500),XIAF(500),FSP(500),
     1              FSPI(500),Q1(500),AU(500)
      DIMENSION     AK(500),AI(500),NI1R(500),NI2R(500)
      DIMENSION     FFOUT(N1X,30),LAOUT(20)
      DIMENSION     QA(KCC,NOU),RHOT(NOU,LMM)
      DIMENSION     GGRI(KAA,NOU,L1X),GGRIT(KAA,NOU,L1X),KKA(KAA)
      DIMENSION     FFRIT(KJL),FFAB(LXA*4,4,NXA)
	DIMENSION     AMPEW(LXA,4,4)
      COMPLEX       GGRI,GGRIT,FFRIT,FFAB,FFOUT,AMPEW
      COMPLEX       ZERO,TTI,TRI4,TRI5,TRI6,URI1
      DOUBLE PRECISION FFMU,FFMU1,FFMU2,RROOT
CCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCC 
CCCCCC      RHOE(N,NH,LAMP1)      IS USED IN FFCALE, TRECAL AND PDENST
CCCCCC      TRHO(N1 OR NB,NH,KB)  IS USED IN FFCALE AND TRECAL
CCCCCC      GWT (N1 OR NB,NH,NWT) IS USED IN FFCALE AND TRECAL
CCCCCC      GGRI(KA,NH,NLS)       IS USED IN FFCALE ONLY
CCCCCC      QA(KC,NH)             IS USED IN FFCALE ONLY
CCCCCC         NWTMAX=(LAM1MX+1)*(LAM1MX+2)/2
CCCCCC         KBMAX=NLSMAX*LAM1MX*(LAM1MX+2)/2
CCCCCC         KCMAX=KBMAX*NOLTR*LAM2MX*(LAM2MX+1)/2    QC  (KC,NH)
CCCCCC         KAMAX=LAMMX*(LAMMX+1)/2                  GGRI(KA,NH)
CCCCCC         KGMAX=KCMAX*LAMP1X
CCCCCC            KB=(KC,NLS,LAM1,LPP)
CCCCCC            KC=(LT,KB,LAM2,LL)
CCCCCC            KA=(LL,LAM)
CCCCCC            KG=(KC,LAM)
CCCCCC            NLS=(LT1,L1,S)
CCCCCC      FFAB(K,M1,NH)        IS USED IN FFCALE ONLY
CCCCCC            KMAX=NBLOCK=NOLA*K MAX
CCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCC
      WRITE(8,800)
 800  FORMAT(//1H ,'FFCALE IS CALLED')
      WRITE(8,801)
 801  FORMAT(1H ,5X,'INPUT INFORMATION FOR EXCHANGE FORM FACTOR')
      IDUM=1
      WRITE(8,802) (LAMMXD(I),I=1,3),MXMAX,MAMAX
 802  FORMAT(1H ,5X,'LAM1MX,LAM2MX,LAMDMX,MXMAX,MAMAX=',6I5)
      WRITE(8,803) NXMIR(1),NXMXR(1),NASTEP,XMESR(1)
 803  FORMAT(1H ,5X,'NAMIN,NAMAX,NASTEP,XEMSH=',3I5,F10.3)
      IF (NASTEP.NE.1) WRITE(8,804)
 804  FORMAT(1H ,5X,'**SORRY, INTERPOLATION IN R_a IS NOT MADE.')
      WRITE(8,815) NONAR
      WRITE(8,805) NBCMI,NBCMX,NBSTEP,XMESR(2)
 805  FORMAT(1H ,5X,'NBCMI,NBCMX,NBSTPE,XMESH=',3I5,F10.3)
      IF (NBSTEP.NE.1) WRITE(8,806)
 806  FORMAT(1H ,5X,'**INTERPOLATION IN R_b IS MADE')
      WRITE(8,807) NXMIR(3),NXMXR(3),IDUM,XMESR(3)
 807  FORMAT(1H ,5X,'N2MIN,N2MAX,N2STEP,XEMSH=',3I5,F10.3)
      WRITE(8,808) NXMIR(4),NXMXR(4),N1STEP,XMESR(4)
 808  FORMAT(1H ,5X,'N1MIN,N1MAX,N1STEP,XEMSH=',3I5,F10.3)
C      IF (N1STEP.NE.1) WRITE(8,809)
 809  FORMAT(1H ,5X,'**INTERPOLATION IN R_1 IS MADE')
      WRITE(8,810) INTRAN,XMESHE
 810  FORMAT(1H ,5X,'INTRAN,XMESHE=',I5,F10.3)
      WRITE(8,811) (KCETN(N),N=1,2)
 811  FORMAT(/1H ,5X,'KCETN(1),KCETN(2)=',2I3)
      IF (KCETN(1).EQ.1) WRITE(9,812)
 812  FORMAT(1H ,5X,'CENTRAL EXCHANGE FF IS NOT CONSIDERED')
      IF (KCETN(2).EQ.1) WRITE(9,813)
 813  FORMAT(1H ,5X,'TENSOR EXCHANGE FF IS NOT CONSIDERED')
 815  FORMAT(1H ,5X,'INTEGRATION RANGE FOR FINAL EXCH FF=',I5)
      KMAS=PMASA+0.001
      IF (KTRLD(1).EQ.3) KMAS=1
CCCCCC
CCCCCC      SECTION 1. CHECK THE FIELD LENGTH OF VARIABLES
CCCCCC
      CALL DCHECK2
CCCCCC
CCCCCC      SECTION 2. CALCULATE THE EFFECTIVE INTERACTION FOR EXCHANGE FF
CCCCCC
      CALL EFFINT(1)
CCCCCC
CCCCCC      SECTION 3. CALCULATE THE PROJ. AND TARGET DENSITIES
CCCCCC
      CALL TRECAL
CCCCCC
CCCCCC      SECTION 4. DEFINE BASIC VARIABLES AND CONSTANTS
CCCCCC
      REWIND 13
      REWIND 14
      ZERO=(0.0,0.0)
      TTI=(0.0,1.0)
      LAP1MI=LDWMIR(1)+1
      LAP1MX=LDWMXR(1)+1
      LASTEP=LDWSTR(1)
      LBP1MI=LDWMIR(2)+1
      LBP1MX=LDWMXR(2)+1
      LBSTEP=LDWSTR(2)
      NOLA=(LAP1MX-LAP1MI)/LASTEP+1
      NOLB=(LBP1MX-LBP1MI)/LBSTEP+1
      XMESA=XMESR(1)
      NMXA=NXMXR(1)
      NMIA=NXMIR(1)
      XMESX=XMESR(3)
      NMXX=NXMXR(3)
      NMIX=NXMIR(3)
      XMES1=XMESR(4)
      N1MAX=NXMXR(4)
      N1MIN=NXMIR(4)
      XMESB=XMESR(2)
      NMXB=NXMXR(2)
      NMIB=NXMIR(2)
      NONB=(NBCMX-NBCMI)/NBSTEP+1
      NBCMX=(NONB-1)*NBSTEP+NBCMI
      KFMAX=NOLTR
      LTMIN=LTR(1)
      LTMAX=LTR(NOLTR)
      LTMXP1=LTMAX+1
      MP1MAX=MIN0(LTMXP1,MXMAX+1)
CCCCCC
      XMES13=XMES1/3.0
      R2MX=XMESX*FLOAT(NMXX)
      R2MXSQ=R2MX*R2MX
      ALPH=PMASA
      ALPHSQ=ALPH*ALPH
      RHOMX=RHED(INTRAN)
      RHODMX=RHOMX/ALPH
      RHDXSQ=RHODMX**2
      NONBNH=NONB*INTRAN
	NASTEP=1 !WE SET HERE NO MATTER WHAT THE INPUT IS.
      NONAM=(NONA-1)/NASTEP+1
      LAM1MX=LAMMXD(1)+1
      LAM2MX=LAMMXD(2)+1
      KBMAXT=(NLSMAX*((LAM1MX+1)**2))/2
CCCCCC
      L1MAX=L1R(1)
      DO 92 NLS=1,NLSMAX
      IF(L1MAX.LT.L1R(NLS)) L1MAX=L1R(NLS)
   92 CONTINUE
      M2MAX=LAM2MX
      LPP1MX=L1MAX+LAM1MX
      LAMP1X=LAMMXD(3)+1
      IF(KTRLD(1).NE.2) GO TO 94
      DO 93 NLT=1,NOLTR
      DO 93 NB=1,NONB
   93 GGRIE(NLT,NB)=(0.0,0.0)
   94 CONTINUE
CCCCCC
CCCCCC      SECTION 5. CALCULATE THE CENTRAL AND TENSOR EXCHANGE FF
CCCCCC
CCCCCC            KCT=1 IS FOR CENTRAL EXCHANGE FORM FACTOR   
CCCCCC                  A  NARROW RH-RANGE SHOULD BE TAKEN
CCCCCC            KCT=2 IS FOR TENSOR  EXCHANGE FORM FACTOR        
CCCCCC                  A  LONG   RH-RANGE SHOULD BE TAKEN
CCCCCC
      DO 1000 KCT=1,2
      IF(KCETN(KCT).EQ.1) GO TO 1000
      KCT1=KCT
CCCCCC
      IF(KCT.EQ.1.AND.KTRLD(1).EQ.2) LAMMXD(3)=0
      IF(KCT.EQ.2.AND.KTRLD(1).EQ.2) LAMMXD(3)=2
CCCCCC
      NGAUS=NGAUSR
      CALL GAUSF(NGAUS,RTS,WGT)
CCCCCC
      IF (KCT.EQ.1) WRITE(8,828) KCT 
      IF (KCT.EQ.2) WRITE(8,829) KCT 
      WRITE(8,827) LAM1MX,LAM2MX,LAMMXD(1),LAMMXD(2),NGAUS
  827 FORMAT(1H ,5X,'(FFCALE)LAM1MX,LAM2MX,LAMMXD(1,2),NGAUS=',5I3)
  828 FORMAT(/1H ,5X,'CENTRAL EXCHANGE FORM FACTOR CALCULATION, KCT=',
     1       I3)
  829 FORMAT(/1H ,5X,'TENSOR EXCHANGE FORM FACTOR CALCULATION, KCT=',I3)
CCCCCC
      CALL GFAC(KCT1)
CCCCCC
      NBLOCK=NOLA*NOLTR
      IF(KCT.EQ.2) NBLOCK=NOLA*NLSMAX
CCCCCC
CCCCCC      SECTION 6. CALCULATE G-FACTORS 
CCCCCC                   [BIG NB-LOOP STARTS (UP TO 900)]
CCCCCC
      DO 100 KA=1,KAMAX
  100 KKA(KA)=1
      NBM=0
      DO 900 NB=NBCMI,NBCMX,NBSTEP
      NBM=NBM+1
      RB=XMESB*FLOAT(NB)
      RBSQ=RB*RB
      NACENT=(RB+0.000001)/XMESA
CCCCCC
CCCCCC      CALCULATION OF QA FOR A GIVEN RB
CCCCCC
      DO 102 KC=1,KCMAX
      DO 102 NH=1,INTRAN
      QA(KC,NH)=0.0
  102 CONTINUE
CCCCCC
      IF(KMAS.NE.1) THEN !NUCLEON SCATTERING
CCCCCC
      F1=2.0
      DO 300 N1=N1MIN,N1MAX
      N1M=N1-N1MIN+1
      R1=XMES1*FLOAT(N1)
      AB1=ABS(R1-RB)
      IF(AB1.GE.R2MX) GO TO 300
      R1SQ=R1*R1
      F1=6.0-F1
      FAC1=R1SQ*XMES13*F1
      R1RB2=R1*RB*2.0
      FMUI=(R1SQ+RBSQ-R2MXSQ)/R1RB2
      IF(FMUI.GE.1.0) GO TO 300
      IF(FMUI.LT.-1.0) FMUI=-1.0
      RANGE=1.0-FMUI
      RANG2=RANGE*0.5
CCCCCC
      DO 190 NG=1,NGAUS
      ROOT=1.0-(1.0-RTS(NG))*RANG2
      WGT1=WGT(NG)*RANG2
      FAC2=WGT1*FAC1
      R2SQ=R1SQ+RBSQ-R1RB2*ROOT
      R2=SQRT(R2SQ)
      X2=R2/XMESX
      N2=X2
      IF(N2.LT.1) N2=1
      IF(N2.GT.NMXX-1) GO TO 190
      FN2=N2
      FMU=(R1*ROOT-RB)/R2
      FFMU=FMU
      CALL YLCAL(FFMU,LAM2MX,LAM2MX,P)
      DO 111 LAM2P1=1,LAM2MX
      DO 111 M1=1,LAM2P1
  111 PP(LAM2P1,M1)=P(LAM2P1,M1)
      RROOT=ROOT
      CALL YLCAL(RROOT,LPP1MX,M2MAX,P)
      DO 112 LAM2P1=1,LAM2MX
      DO 112 NH=1,INTRAN
      RHOT1=RHOE(N2  ,NH,LAM2P1)
      RHOT2=RHOE(N2+1,NH,LAM2P1)
      RHOT(NH,LAM2P1)=RHOT1+(RHOT2-RHOT1)*(X2-FN2)
  112 CONTINUE
CCCCCC
      DO 130 KC=1,KCMAX
      KB=KBC(KC)
      LAM2P1=LAM2PC(KC)
      LPP1=LPP1C(KC)
      DO 128 M2=1,LAM2P1
      C1=CLEBQ(KC,M2)
      FAC3=FAC2*PP(LAM2P1,M2)*P(LPP1,M2)*C1
      DO 126 NH=1,INTRAN
      QA(KC,NH)=QA(KC,NH)+TRHO(N1,NH,KB)*RHOT(NH,LAM2P1)*FAC3
  126 CONTINUE
  128 CONTINUE
  130 CONTINUE
CCCCCC
  190 CONTINUE
  300 CONTINUE
      ELSE
CCCCCC
CCCCCC      NUCLEON-NUCLEUS CASE
CCCCCC
      F1=2.0
      DO 200 N1=N1MIN,N1MAX
      N1M=N1-N1MIN+1
      R1=XMES1*FLOAT(N1)
      AB1=ABS(R1-RB)
      IF(AB1.GE.R2MX) GO TO 200
      R1SQ=R1*R1
      F1=6.0-F1
      FAC1=R1SQ*XMES13*F1
      R1RB2=R1*RB*2.0
      FMUI=(R1SQ+RBSQ-R2MXSQ)/R1RB2
      IF(FMUI.GE.1.0) GO TO 200
        DO 160 NH=1,INTRAN                   
          RH=XMESH*FLOAT(NH)                 
          RHSQ=RH*RH                         
          FMU=(RBSQ+R1SQ-RHSQ)/R1RB2               
          IF (ABS(FMU).GT.1.0)  GO TO 160          
          WGT1=1.0/(RB*R1*RH)                                           
          FMU2=(R1*FMU-RB)/RH                          
          IF (ABS(FMU2).GT.1.0) GO TO 160              
          KP1=3
          FFMU2=FMU2                              
          CALL YLCAL(FFMU2,KP1,KP1,P)             
          DO 142 LAM2P1=1,KP1                     
          DO 142 M2X   =1,LAM2P1                  
            PP(LAM2P1,M2X)=P(LAM2P1,M2X)          
  142     CONTINUE
          FFMU=FMU 
          CALL YLCAL(FFMU,LPP1MX,LPP1MX,P)                              
          DO 150 KC=1,KCMAX                                             
            KB=KBC(KC)                                                  
            LAM2P1=LAM2PC(KC)                                           
            H1SQ=LAM2P1*2-1                                             
            H1=SQRT(H1SQ)                                               
            FAC2=FAC1*WGT1*H1                                           
            S1=(-1.0)**(LAM2P1-1)                                       
            LPP1=LPP1C(KC)                                              
            DO 148 M2X=1,LAM2P1                                         
              C1=CLEBQ(KC,M2X)                                          
              FAC3=FAC2*PP(LAM2P1,M2X)*P(LPP1,M2X)*C1*S1                
              QA(KC,NH)=QA(KC,NH)+FAC3*TRHO(N1M,NH,KB)
  148       CONTINUE
  150     CONTINUE
  160   CONTINUE
  200 CONTINUE
      ENDIF
CCCCCC
      ISTP=(INTRAN+9)/10
      IF(KTLOUT(3).GE.2) THEN
      IF(MOD(NB,10).EQ.0) THEN
      WRITE(8,860)
      DO 306 KC=1,KCMAX
      WRITE(8,850) NB,KC,(QA(KC,NH),NH=1,INTRAN,ISTP)
  306 CONTINUE
      ENDIF
	ENDIF
  850 FORMAT(1H ,'NB,KC=',I3,2X,I3,10E10.3)
 860  FORMAT(/1H ,5X,'QA(KC,NH) AT NB')
CCCCCC
CCCCCC      SECTION 7. CALCULATE THE G-FACTOR
CCCCCC
  310 DO 315 NLS=1,NLSMAX
      DO 315 KA=1,KAMAX
      DO 315 NH=1,INTRAN
  315 GGRI(KA,NH,NLS)=(0.0,0.0)
      DO 320 NLS=1,NLSMAX
      DO 320 KG=1,KGMAX
      KA=KAD(KG,NLS)
      IF(KA.EQ.0) GO TO 320
      NLT=NLTD(NLS)
      A1=ALPHA(NLS,NLT)
      IF(KCT.EQ.2) A1=1.0
C     NOTE THAT FOR KCT=2, A1 FACTOR IS MULTIPLIED IN TENSOR
C                          OR LATER AFTER S.N. 750 (FOR NR CASE)
      COEF1=COEF(KG)*A1
      KKA(KA)=0
      KC=KCD(KG)
      NI1=NINTC(KC)+KCT-1
      NI2=NI1+6
      NI1R(KA)=NI1
      NI2R(KA)=NI2
      DO 318 NH=1,INTRAN
      URI1=VV(NH,NI1)+VV(NH,NI2)*TTI
      GGRI(KA,NH,NLS)=GGRI(KA,NH,NLS)+QA(KC,NH)*COEF1*URI1  
  318 CONTINUE
CCCCCC
      IF (KTLOUT(3).GE.2) THEN
      IF(MOD(NB,10).EQ.0) THEN
      WRITE(8,851) KG,KA,NLTD(KG),KC,COEF(KG),QA(KC,1),GGRI(KA,1,NLS)
	ENDIF
	ENDIF
  851 FORMAT(1H ,'KG,KA,NLT,KC,COEF,QA,GGRI=',4I4,5E10.3)
CCCCCC
  320 CONTINUE
CCCCCC
      IF(KTLOUT(13).NE.0) THEN
      IF(MOD(NB,10).EQ.0) THEN
      IPRINT=MIN0(INTRAN,30) 
      DO 350 NLS=1,NLSMAX
      DO 350 KA=1,KAMAX
      LAM=LAMD(KA)
      IF(LAM.EQ.0)
     1     WRITE(8,852) NB,NLS,LAM,(GGRI(KA,NH,NLS),NH=1,IPRINT)
  350 CONTINUE
      ENDIF
	ENDIF
  852 FORMAT(1H ,'NB,NLS,LAM=',3I3,10E10.3/(21X,10E10.3))
CCCCCC
CCCCCC      SECTION 8. CALCULATE C-FACTORS
CCCCCC              DECOMPOSITION OF RH INTO RA AND RB IN G-FACTOR
CCCCCC
      IF(KTRLD(1).EQ.2) GO TO 750 !NO-RECOIL APPROXIMATION
CCCCCC
      NLSLTMX=MAX0(NLSMAX,NOLTR)
      NBLOCK=NOLA*NLSLTMX
      M1X=MIN0(LAMP1X,L1MAX+1)
      DO 406 NAM=1,NONAM
      DO 406 M1=1,M1X
      DO 406 NB1=1,NBLOCK
      FFAB(NB1,M1,NAM)=0.0
  406 CONTINUE
      IF(NB.EQ.30) 
     1     WRITE(8,853) NBLOCK,M1X,NONA,NONAM,NONAR,NONAH,NACENT
  853 FORMAT(1H ,5X,'(FFCALE)NBLOCK,M1X,NONA,NONAM,NONAR,NONAH,NACENT='
     1        ,10I4,'AT NB=30')
CCCCCC
      DO 500 NAM=1,NONAR
      NA=(NAM-1)*NASTEP+NACENT-NONAH
	IF (NA.LE.0) GO TO 500
      IF(NA.LT.NMIA.OR.NA.GT.NMXA) GO TO 500
      RA=XMESA*FLOAT(NA)
      RASQ=RA*RA
      RARB2=RA*RB*2.0
      XMESH=XMESHE
      RHOMX=RHED(INTRAN)
      RHODMX=RHOMX/ALPH
      RHDXSQ=RHODMX**2
      RHDXST=RHDXSQ
      FMUI=(RASQ+RBSQ-RHDXST)/RARB2
      IF(FMUI.GT. 0.9999999999) GO TO 500  
      IF(FMUI.LT.-0.9999999999) FMUI=-1.0
      RANGE=1.0-FMUI
      RANG2=RANGE*0.5
      NMAX1=INTRAN
      DO 408 NH=1,INTRAN
  408 XAF(NH)=RHED(NH)
      DO 410 NG=1,NGAUS
      ROOT=1.0-(1.0-RTS(NG))*RANG2
      RHDSQ=RASQ+RBSQ-RA*RB*2.0*ROOT
      RHSQ=RHDSQ*ALPHSQ
      RH=SQRT(RHSQ)
      XIAF(NG)=RH
      RHD=RH/ALPH
      FMU1=(RB-ROOT*RA)/RHD
      GFT(NG)=FMU1
  410 CONTINUE
      DO 420 NLS=1,NLSMAX
      DO 420 KA=1,KAMAX
      DO 412 NH=1,INTRAN
      AF (NH)= GGRI(KA,NH,NLS)*XAF(NH)
      AFI(NH)=-GGRI(KA,NH,NLS)*XAF(NH)*TTI
  412 CONTINUE
      NGINT=NGAUS
      CALL DSPLS3(XAF,AF ,NMAX1,XIAF,FSP , NGINT,Q1,AU,1)
      CALL DSPLS3(XAF,AFI,NMAX1,XIAF,FSPI, NGINT,Q1,AU,1)
      DO 414 NG=1,NGAUS
      GGRIT(KA,NG,NLS)=(FSP(NG)+FSPI(NG)*TTI)/XIAF(NG)
  414 CONTINUE
  420 CONTINUE
      DO 450 NG=1,NGAUS
      IF(XIAF(NG).GT.RHOMX) GO TO 450
      ROOT=1.0-(1.0-RTS(NG))*RANG2
      WGT1=WGT(NG)*RANG2
      RROOT=ROOT
      CALL YLCAL(RROOT,LAP1MX,M1X,P)
      DO 422 LAP1=1,LAP1MX
      DO 422 M1  =1,M1X
  422 PP(LAP1,M1)=P(LAP1,M1)
      FMU1=GFT(NG)
      FFMU1=FMU1
      CALL YLCAL(FFMU1,LAMP1X,M1X,P)
      DO 440 NLS=1,NLSMAX
      DO 440 KA=1,KAMAX
      IF(KKA(KA).EQ.1) GO TO 440
      LAMP1=LAMD(KA)+1
      TRI4=GGRIT(KA,NG,NLS)
      TRI5=TRI4*WGT1
      LAM=0
      DO 435 LAP1=LAP1MI,LAP1MX,LASTEP
      LAM=LAM+1
      K=(LAM-1)*NLSMAX+NLS
      DO 430 M1=1,M1X
      TRI6=TRI5*PP(LAP1,M1)*P(LAMP1,M1)*CLEBF(KA,M1,NLS)
      FFAB(K,M1,NAM)=FFAB(K,M1,NAM)+TRI6
  430 CONTINUE
  435 CONTINUE
  440 CONTINUE
  450 CONTINUE
  500 CONTINUE
CCCCCC
      DO 700 NAM=1,NONAR 
      NA=(NAM-1)*NASTEP+NACENT-NONAH
      IF (NA.LE.0) GO TO 700
      IF(NA.LT.NMIA.OR.NA.GT.NMXA) GO TO 700
      MEM1=0
      DO 640 JLS=1,JLSMX
      K=KKD(JLS)
      FFRIT(JLS)=0.0
      DO 630 M1=1,M1X
      C1=CCDD(JLS,M1)
      FFRIT(JLS)=FFRIT(JLS)+C1*FFAB(K,M1,NAM)
  630 CONTINUE
CCCCCC
      LAM=LAD(JLS)
      IF(KTLOUT(13).EQ.0) GO TO 640
      KT13=KTLOUT(13)
      LA=LAP1MI+(LAM-1)*LASTEP-1
      IF(MOD(LA,KT13).NE.0.OR.LA.GT.30) GO TO 640
      MEM1=MEM1+1
      FFOUT(NAM,MEM1)=FFRIT(JLS)
      LAOUT(MEM1)=LA
  640 CONTINUE
CCCCCC
      IF(KCT.EQ.1) WRITE (13) (FFRIT(JLS),JLS=1,JLSMX)
      IF(KCT.EQ.2) WRITE (14) (FFRIT(JLS),JLS=1,JLSMX)
  700 CONTINUE
      IF(KCT.EQ.1) JLSCMX=JLSMX
CCCCCC
      KPRINT=KTLOUT(13)
      IF(KPRINT.NE.0) THEN
      DO 720 MEM2=1,MEM1
      WRITE(8,865) LAOUT(MEM2),MEM2,NB,(FFOUT(NAM,MEM2),NAM=1,NONAM,20)
  720 CONTINUE
      ENDIF
  865 FORMAT(//1H ,'LA,NB=',3I3//(5X,12E10.3))
      GO TO 900
CCCCCC
CCCCCC     NO-RECOIL APPROXIMATION  (KTRLD(1)=2 CASE) 
CCCCCC
  750 CONST=SQRT(PI*4.0)/3
      KTRP2=(KCT-1)*2+1
      DO 775 NLS=1,NLSMAX
      L1TWP1=L1R(NLS)*2+1
      DO 770 KA=1,KAMAX
      LAM=LAMD(KA)
      IF(KCT.EQ.1.AND.LAM.NE.0) GO TO 770
      IF(KCT.EQ.2.AND.LAM.NE.2) GO TO 770
      NLT=NLTD(NLS)
	LT=LTR(NLT)
      LTTWP1=LT*2+1
	S1=1      
C	IF(KMAS.EQ.1) S1=(-1.0)**((LT-KPARIT)/2)                                        
      H1SQ=FLOAT(L1TWP1)/FLOAT(LTTWP1)
      H1=SQRT(H1SQ)*CONST*S1
      IF(KCT.EQ.1) GO TO 761
      NLSK=NLSMAX+NLS
      H1=H1*ALPHA(NLSK,NLT)
  761 NMAX1=INTRAN
      DO 762 NH=1,INTRAN
      RHO1=RHED(NH)
      XAF(NH)=RHO1
      AF(NH)=  GGRI(KA,NH,NLS)*XAF(NH)
  762 AFI(NH)=-GGRI(KA,NH,NLS)*XAF(NH)*TTI
      INT1MX=150
      DO 768 INT1=1,2
      XH1=0.01
      X1=0.0
      IF(INT1.EQ.1) GO TO 764
      XH1=0.008
      X1=1.5
  764 DO 766 NH=1,INT1MX
      X1=X1+XH1
  766 XIAF(NH)=X1
      NGINT=INT1MX
      CALL DSPLS3(XAF,AF ,NMAX1,XIAF,FSP ,NGINT,Q1,AU,1)
      CALL DSPLS3(XAF,AFI,NMAX1,XIAF,FSPI,NGINT,Q1,AU,1)
      F1=2.0
      H2=H1*XH1
      DO 767 NH=1,INT1MX
      F1=6.0-F1
      R1=XIAF(NH)**KTRP2
      GGRIE(NLT,NBM)=GGRIE(NLT,NBM)+(FSP(NH)+FSPI(NH)*TTI)*R1*H2*F1
  767 CONTINUE
  768 CONTINUE
  770 CONTINUE
  775 CONTINUE
CCCCCC
  900 CONTINUE
CCCCCC
CCCCCC      END OF RB LOOP
CCCCCC
 1000 CONTINUE
CCCCCC
CCCCCC      END OF KCT LOOP
CCCCCC      
      IF (KTRLD(1).EQ.2) THEN
	  CALL PACALD(2)
	ELSE
        CALL TENSOR
	  CALL PACALE
	ENDIF
CCCCCC
      RETURN 
      END


      SUBROUTINE TRECAL
CCCCCC
      PARAMETER(NHS=9,NPS=9,LXA=150,LXB=150,LPH=10,LMM=4,LTL=9)
      PARAMETER(NXA=420,NXB=140,NIN=300,NOU=300,N1X=140)
      PARAMETER(KFM=10,KAA=40,KBB=30,KCC=80,KGG=125,KJL=600,KTEN=5000)
      PARAMETER(LMJ=10,LRP=11,L1X=10,L2X=60,LM1=5,LM2=30,LAB=2000)
CCCCCC	
      COMMON/CNST  /FACLOG(500),PI,HBAR,AMAS,WNUNIT,FINE
      COMMON/DWCC/  LDWMIR(4),LDWMXR(4),WN(4),LDWSTR(4),CE(4),CFUNIR(4),
     1              ECM(4),XMESR(4),NXMXR(4),NXMIR(4),NOEXP,MXSTEP,
     2              TMASA,TMASB,TMASX,TMASY,PMASA,PMASB,PMASX,PMASY,
     3              TZA,TZB,TZX,TZY,
     4              PZA,PZB,PZX,PZY,XBARD(4),XBARID(4),WNXD(20),EXPD(20)
      COMMON/CNTRL/ KTRLD(9),KTLOUT(24),NERUN,KRTYPE
      COMMON/FFCC/  VRANG(6),VSTR(12,6),VV(300,24),XMESH,XMESC,
     1              XMESHD,XMESHE,RHED(300),
     2              NBCMI,NBCMX,NONB,NBSTEP,LASTEP,LBSTEP,MAMAX,MXMAX,
     3              MP1MAX,NOLA,NOLB,INTRAN,LMI,LMX,KCETN(2),
     4              NCMAX,NCMIN,LDMAX,JATRTY,NONA,NONAH,NONAR,NASTEP,
     5              NHDMX,NHEMX,NGAUSR,NBSTPD,NBSTPE,N1STEP,JATW,ISATW
      COMMON/CDENS/ RHOE(NXA,NIN,LMM),USAVEX(4*NXA),SPEC(4),
     1              DENSTY(NXA),LAMMXD(3),LBXD(4),NOSTX,NDMY
      COMMON/SPSTAT/EET,SPECTA(LPH),ESP(LPH),ESH(LPH),NSP(LPH),LSP(LPH),
     1              JTWP(LPH),NSH(LPH),LSH(LPH),JTWH(LPH),IPAIR,NOSP,
     2              NOSH,NPST(LPH),NHST(LPH),NPAIRD,L1R(8),ISR(8),
     3              ITR(8),NLSMAX,JT,KPARIT,IST,NOLTR,N1,LTR(8),
     4              ITP(LPH),ITH(LPH),ITZP(LPH),ITZH(LPH)
      COMMON/CCKF/  L1KFD(KFM),ISKFD(KFM),KKFD(KFM),LTKFD(KFM),KFMAX,
     1              ITKFD(KFM),NLSKFD(KFM),NLTKFD(KFM),LTMIM,LTMAX
      COMMON/CGFAC /KAMAX,KGMAX,KCMAX,JLSMX,KBBSD(10),
     1              KBC(KCC),LAM2PC(KCC),LPP1C(KCC),LLP1D(KCC),
     2              NINTC(KCC),KAD(KGG),KCD(KGG),NLSD(KGG),LAMD(KAA),
     3              CLEBQ(KCC,5),CLEBF(KAA,5,5),COEF(KGG),CCDD(KJL) 
      COMMON/CGGR/  GGRIE(L1X,N1X)
      COMPLEX       GGRIE
      COMMON/CBST/  USAVP(NPS*NXA),USAVH(NHS*NXA),CY(LXA)
      COMPLEX       CY 
      COMMON/CTRHO/ TRHOPH(N1X,NIN,KBB,LPH)
      COMMON/DISW / DISWB(LXB*NXB),DISWA(LXA*NXA)
      COMPLEX       DISWA,DISWB
      COMMON/TREDEN/GWT(N1X,NIN,LM2),TRHO(N1X,NIN,KBB)	  
      DIMENSION     L9(10)
CCCCC
CCCCC           CALCULATIONS OF TRANSITION DENSITIES
CCCCC
CCCCC          IF(KTRLD(1).EQ.2)    LAMMXD(3)=0            
CCCCC
      KMAS=PMASA+0.001
      IF (KTRLD(1).EQ.3) KMAS=1
CCCCCC
      CALL PDENST(1)
CCCCCC
      N1MAX=NXMXR(4)
      LAM1MX=LAMMXD(1)+1
      LAM2MX=LAMMXD(2)+1
      KBMAXT=(NLSMAX*((LAM1MX+1)**2))/2
      DO 35 KB=1,KBMAXT
      DO 35 NH=1,INTRAN
      DO 35 N1=1,N1MAX
   35 TRHO(N1,NH,KB)=0.0
      NGWT=LAM1MX*(LAM1MX+1)/2
      JTTW=JT*2
      ITZ1=PZA-PZB+0.01
      KB=0
      MEXP=0
      DO 80 NLS=1,NLSMAX
      IS=ISR(NLS)
      ISTW=IS*2
      L1=L1R(NLS)
      IT1=ITR(NLS)
      L1TW=L1*2
      NPAIR=NPAIRD
      KBBSD(NLS)=KB
      DO 78 LAM1P1=1,LAM1MX
      LAM1=LAM1P1-1
      LAM1TW=LAM1*2
      LPP=L1-LAM1-1
      NLPPX=2*LAM1+1
      DO 76 NLPP=1,NLPPX
      LPP=LPP+1
      LPPTW=LPP*2
      IF(MOD(LAM1+LPP,2).NE.KPARIT) GO TO 76                 
      IF(LPP.GT.(L1+LAM1))          GO TO 76                 
      IF(LPP.LT.IABS(L1-LAM1))      GO TO 76                 
      IF(LPP.LT.0) GO TO 76
      KB=KB+1
      MEXP=MEXP+1
      IRU=0
      DO 70 I=1,NPAIR
      NP1=NPST(I)
      NH1=NHST(I)
      A1=SPECTA(I)
      IRU=IRU+1
      N1BASE=(NP1-1)*N1MAX
      N2BASE=(NH1-1)*N1MAX
      LP=LSP(NP1)
      LH=LSH(NH1)
      LPTW=LP*2
      LHTW=LH*2
      JPTW=JTWP(NP1)
      JHTW=JTWH(NH1)
      NNN=NH1
      LLL=LH
      LLP=LP
      LE1=LLL
      LLLTW=LLL*2
      LLPTW=LLP*2
      IF(IRU.EQ.1) GO TO 43
      II=I-1
      NEXP=NHST(II)
      IF(NH1.EQ. NEXP) GO TO 50
   43 CALL DENST(NNN,LLL)
   50 CONTINUE
      PHASE=1.0
      IF(IT1.EQ.1.AND.ITZ1.EQ.0.AND.ITZP(NP1).EQ.-1) PHASE=-1.0
      L9(1)=LPTW
      L9(2)=1
      L9(3)=LHTW
      L9(4)=1
      L9(5)=JPTW
      L9(6)=JHTW
      L9(7)=L1TW
      L9(8)=ISTW
      L9(9)=JTTW
      CALL NINEJ(L9,FACLOG,U9) 
      T1=U9
      H1=(JPTW+1)*(JHTW+1)*(L1TW+1)*(ISTW+1)
      U9=T1*SQRT(H1)
      K11=LP+LH+KPARIT
      K1=-KPARIT
      IF(MOD(K11,2).NE.0) GO TO 70
C     S1=1-MOD(K1/2,2)*2
      S1=1.0
      LHP=LLL-LAM1-2
      NLH=LAM1P1
      DO 54 NLH1=1,LAM1P1
      LHP=LHP+2
      S2=(-1.0)**LHP
      NGW=(LAM1*LAM1P1)/2+NLH1
      IF(LHP.LT.0) GO TO 54
      IF(LHP.GT.(LLP+LPP).OR.LHP.LT.IABS(LLP-LPP)) GO TO 54
      LHPTW=LHP*2
      IA=LPPTW
      IB=LHPTW
      IC=LLPTW
      CALL CLEBZ(IA,IB,IC,FACLOG,RAC) 
      C1=RAC
      H1=(LHPTW+1)*(LLLTW+1)*(LPPTW+1)
      C2=SQRT(H1)
      IA=LPPTW
      IB=LHPTW
      IC=L1TW
      ID=LLLTW
      IE=LLPTW
      IFF=LAM1TW
      CALL RAC7(IA,IB,IC,ID,IE,IFF,FACLOG,RAC) 
      FAC1=A1*U9*S1*S2*C1*C2*RAC
      NCORR=LP
      PHACO=1-2*MOD(NCORR,2)
      IF(KMAS.EQ.1) PHACO=PHACO*(-1.0) !NUCLEON SCATTERING
      FAC1=FAC1*PHACO
      DO 52 NH=1,INTRAN
      DO 52 N1=1,N1MAX
      N1M=N1+N1BASE
      N2M=N1+N2BASE
      U2=USAVP(N1M)
      TRHO(N1,NH,KB)=TRHO(N1,NH,KB)+U2*GWT(N1,NH,NGW)*FAC1*PHASE
   52 CONTINUE
   54 CONTINUE
   70 CONTINUE
   76 CONTINUE
   78 CONTINUE
   80 CONTINUE
      KBMAX=KB
CCCCCC
      IF(KBMAX.GT.KBB) THEN
      WRITE(8,880)
	STOP
	ENDIF
      IF (KTLOUT(3).GE.1) THEN
      ISTP=(INTRAN+9)/10
      DO 88 KB=1,KBMAX
      WRITE (8,881) KB,INTRAN,ISTP
      DO 86 N1=10,50,40
      WRITE (8,882) N1,(TRHO(N1,NH,KB),NH=1,INTRAN,ISTP)
   86 CONTINUE
   88 CONTINUE
      ENDIF
  880 FORMAT(1H ,'DIM. OF KBMAX IS OVER KBB, INCREASE THE DIM. OF TRHO')
  881 FORMAT(/1H ,'TRANSITION DENSITY FOR KB=',I3,2X,'INTRAN,ISTP=',
     1      2I3,'  (TRECAL)')
  882 FORMAT(1H ,'N1=',I4,10E10.3)
CCCCCC
      RETURN
      END
 

      SUBROUTINE DENST(NNN,LLL)
CCCCCC
      PARAMETER(NHS=9,NPS=9,LXA=150,LXB=150,LPH=10,LMM=4,LTL=9)
      PARAMETER(NXA=420,NXB=140,NIN=300,NOU=300,N1X=140)
      PARAMETER(KFM=10,KAA=40,KBB=30,KCC=80,KGG=125,KJL=600,KTEN=5000)
      PARAMETER(LMJ=10,LRP=11,L1X=10,L2X=60,LM1=5,LM2=30,LAB=2000)
CCCCCC
      COMMON/CNST  /FACLOG(500),PI,HBAR,AMAS,WNUNIT,FINE
      COMMON/BSX/   URSAVE(500),ENEPT,VNEPT,VSOR,DFNR,DFNSO,RZR,RZSO,
     1              RZC,XMES2,Q,FTR,NODER,LBTR,JBTRTW,NXRAWF,KTRL4,
     2              KOPOT,LBTRY,JBTWY
      COMMON/DWCC/  LDWMIR(4),LDWMXR(4),WN(4),LDWSTR(4),CE(4),CFUNIR(4),
     1              ECM(4),XMESR(4),NXMXR(4),NXMIR(4),NOEXP,MXSTEP,
     2              TMASA,TMASB,TMASX,TMASY,PMASA,PMASB,PMASX,PMASY,
     3              TZA,TZB,TZX,TZY,
     4              PZA,PZB,PZX,PZY,XBARD(4),XBARID(4),WNXD(20),EXPD(20)
      COMMON/CNTRL/ KTRLD(9),KTLOUT(24),NERUN,KRTYPE
      COMMON/FFCC/  VRANG(6),VSTR(12,6),VV(300,24),XMESH,XMESC,
     1              XMESHD,XMESHE,RHED(300),
     2              NBCMI,NBCMX,NONB,NBSTEP,LASTEP,LBSTEP,MAMAX,MXMAX,
     3              MP1MAX,NOLA,NOLB,INTRAN,LMI,LMX,KCETN(2),
     4              NCMAX,NCMIN,LDMAX,JATRTY,NONA,NONAH,NONAR,NASTEP,
     5              NHDMX,NHEMX,NGAUSR,NBSTPD,NBSTPE,N1STEP,JATW,ISATW
      COMMON/CDENS/ RHOE(NXA,NIN,LMM),USAVEX(4*NXA),SPEC(4),
     1              DENSTY(NXA),LAMMXD(3),LBXD(4),NOSTX,NDMY
      COMMON/SPSTAT/EET,SPECTA(LPH),ESP(LPH),ESH(LPH),NSP(LPH),LSP(LPH),
     1              JTWP(LPH),NSH(LPH),LSH(LPH),JTWH(LPH),IPAIR,NOSP,
     2              NOSH,NPST(LPH),NHST(LPH),NPAIRD,L1R(8),ISR(8),
     3              ITR(8),NLSMAX,JT,KPARIT,IST,NOLTR,N1,LTR(8),
     4              ITP(LPH),ITH(LPH),ITZP(LPH),ITZH(LPH)
      COMMON/OPTL/  THMIN,THMAX,THIND
      COMMON/POTCC/ VA,VB,VX,VY,WA,WB,WX,WY ,WAS,WBS,WXS,WYS ,ARA,ARB,
     1              ARX,ARY,AIA,AIB,AIX,AIY,AISA,AISB,AISX,AISY,RZRA,
     2              RZRB,RZRX,RZRY,RZIA,RZIB,RZIX,RZIY,RZISA,RZISB,
     3              RZISX,RZISY,RZCA,RZCB,RZCX,RZCY,IDA,IDB,IDX,IDY,
     4              VRIT(900),NXMN,NXMX
      COMPLEX       VRIT
      COMMON/ANGLC/ NTHEB,NOTHE,THEB,DTHEB
      COMMON/CBST/  USAVP(NPS*NXA),USAVH(NHS*NXA),CY(LXA)
      COMPLEX       CY
      COMMON/DISW / DISWB(LXB*NXB),DISWA(LXA*NXA)
      COMPLEX       DISWA,DISWB
      COMMON/TREDEN/GWT(N1X,NIN,LM2),TRHO(N1X,NIN,KBB)	        
      DIMENSION     P(130,30),PP(130,10)
      DIMENSION     RTS(96),WGT(96)
      DIMENSION     SSUM(20),HATD(20),C(100),PD(40,10,10)
      DOUBLE PRECISION RROOT,FFMU
CCCCCC
      KMAS=PMASA+0.001
      IF (KTRLD(1).EQ.3) KMAS=1
      LAMMAX=LAMMXD(1)
      SQPAI=SQRT(PI)
      TWPAI=PI*2.0
      SQRT2=1.0/SQRT(2.0)
CCCCCC
      NGAUS=NGAUSR
      CALL GAUSF(NGAUS,RTS,WGT)
CCCCCC
      XMES2=XMESR(4)
      I=1
      LAMP1X=LAMMAX+1
      N2MAX=NXMXR(4)
      XMES2P=XMESR(4)
      JLSMAX=(LAMP1X*(LAMP1X+1))/2
      N2MXM1=N2MAX-1
      N2MXM2=N2MAX-2
      DO 13 N2=1,N2MAX
      DO 13 NH=1,INTRAN
      DO 13 JLS=1,JLSMAX
      GWT(N2,NH,JLS)=0.0
   13 CONTINUE
CCCCCC
      NN=NNN
      LBTR=LLL
      LP1MX=LBTR+1
      MP1MX=LP1MX
      FLBTW1=LBTR*2+1
      K=0
      JLS=0
      DO 20 LAMP1=1,LAMP1X
        LAMD=LAMP1-1
        NLDMX=LAMP1
        HLAMD=TWPAI/FLBTW1
        LD=LBTR-LAMD-2
        DO 19 NLD=1,NLDMX
         JLS=JLS+1
         LD=LD+2
         T2=FLOAT(LD*2+1)
         H1=SQRT(ABS(T2))
         HAT=H1*SQRT(FLBTW1)
         HATD(JLS)=HAT
         LDP1=LD+1
         IA=LD*2
         IB=LAMD*2
         IC=LBTR*2
         ID=0
         T1=1.0
         DO 18 M1=1,LAMP1
           K=K+1
           C(K)=0.0
           IF(LD.LT.0) GO TO 18
           IE=(M1-1)*2
           IFF=IE
           CALL CLEB(IA,IB,IC,ID,IE,IFF,FACLOG,RAC) 
           S1=1.D0
           IF (KMAS.EQ.1) S1=1-2*MOD(M1-1,2) !NUCLEON SCATTERING
           C(K)=RAC*T1*H1*HLAMD*S1
           T1=2.0
   18    CONTINUE
   19   CONTINUE
   20 CONTINUE
      S1=1.0
      IF(KMAS.EQ.1) S1=-1.0  !NUCLEON SCATTERING
      DO 25 NG=1,NGAUS
      ROOT=RTS(NG)
      RROOT=ROOT
      CALL YLCAL(RROOT,LAMP1X,LAMP1X,P)
      DO 24 LAMP1=1,LAMP1X
      DO 24 M1=1,LAMP1
      PD(NG,LAMP1,M1)=P(LAMP1,M1)
   24 CONTINUE
   25 CONTINUE
      N2BASE=(NN-1)*N2MAX
      RH=0.0
      DO 80 NH=1,INTRAN
      RH=RHED(NH)
      RHSQ=RH*RH
      R2P=0.0
      DO 70 N2P=1,N2MAX
      R2P=R2P+XMES2P
      R2PSQ=R2P*R2P
      R2PRH=R2P*RH*2.0*S1
      DO 30 JLS=1,JLSMAX
   30 SSUM(JLS)=0.0
      DO 60 NG=1,NGAUS
      ROOT=RTS(NG)
      R2=SQRT(RHSQ+R2PSQ+R2PRH*ROOT)
      X2=R2/XMES2
      N2=X2
      IF(N2.LT.1) N2=1
      IF(N2.GT.N2MXM2) GO TO 60
      FN2=N2
      P2=X2-FN2
      P21=P2-1.0
      P22=P2-2.0
      A0=P21*P22*0.5
      A1=-P2*P22
      A2=P2*P21*0.5
      N3=N2+N2BASE
      U2=USAVH(N3)*A0+USAVH(N3+1)*A1+USAVH(N3+2)*A2
      U3=U2*WGT(NG)
      FMU=(R2P+RH*ROOT*S1)/R2
      IF (ABS(FMU).GT.1.0) GO TO 60
      FFMU=FMU
      CALL YLCAL(FFMU,LP1MX,MP1MX,P)
      J=0
      K=0
      DO 40 LAMP1=1,LAMP1X
        DO 39 NLD=1,LAMP1
        J=J+1
          DO 38 M1=1,LAMP1
            K=K+1
            SSUM(J)=SSUM(J)+C(K)*U3*P(LP1MX,M1)*PD(NG,LAMP1,M1)
   38     CONTINUE
   39   CONTINUE
   40 CONTINUE
   60 CONTINUE
      JLS=0
      DO 65 LAMP1=1,LAMP1X
      DO 62 NLD=1,LAMP1
      JLS=JLS+1
      GWT(N2P,NH,JLS)=SSUM(JLS)
   62 CONTINUE
   65 CONTINUE
   70 CONTINUE
   80 CONTINUE
CCCCCC
      RETURN
      END


      SUBROUTINE GFAC(KCT)
CCCCCC
      PARAMETER(NHS=9,NPS=9,LXA=150,LXB=150,LPH=10,LMM=4,LTL=9)
      PARAMETER(NXA=420,NXB=140,NIN=300,NOU=300,N1X=140)
      PARAMETER(KFM=10,KAA=40,KBB=30,KCC=80,KGG=125,KJL=600,KTEN=5000)
      PARAMETER(LMJ=10,LRP=11,L1X=10,L2X=60,LM1=5,LM2=30,LAB=2000)
CCCCCC	
      COMMON/CNST  /FACLOG(500),PI,HBAR,AMAS,WNUNIT,FINE
      COMMON/DWCC/  LDWMIR(4),LDWMXR(4),WN(4),LDWSTR(4),CE(4),CFUNIR(4),
     1              ECM(4),XMESR(4),NXMXR(4),NXMIR(4),NOEXP,MXSTEP,
     2              TMASA,TMASB,TMASX,TMASY,PMASA,PMASB,PMASX,PMASY,
     3              TZA,TZB,TZX,TZY,
     4              PZA,PZB,PZX,PZY,XBARD(4),XBARID(4),WNXD(20),EXPD(20)
      COMMON/CNTRL/ KTRLD(9),KTLOUT(24),NERUN,KRTYPE
      COMMON/FFCC/  VRANG(6),VSTR(12,6),VV(300,24),XMESH,XMESC,
     1              XMESHD,XMESHE,RHED(300),
     2              NBCMI,NBCMX,NONB,NBSTEP,LASTEP,LBSTEP,MAMAX,MXMAX,
     3              MP1MAX,NOLA,NOLB,INTRAN,LMI,LMX,KCETN(2),
     4              NCMAX,NCMIN,LDMAX,JATRTY,NONA,NONAH,NONAR,NASTEP,
     5              NHDMX,NHEMX,NGAUSR,NBSTPD,NBSTPE,N1STEP,JATW,ISATW
      COMMON/CNORE/ FACNR,LRP1MX
      COMMON/CDENS/ RHOE(NXA,NIN,LMM),USAVEX(4*NXA),SPEC(4),
     1              DENSTY(NXA),LAMMXD(3),LBXD(4),NOSTX,NDMY
      COMMON/SPSTAT/EET,SPECTA(LPH),ESP(LPH),ESH(LPH),NSP(LPH),LSP(LPH),
     1              JTWP(LPH),NSH(LPH),LSH(LPH),JTWH(LPH),IPAIR,NOSP,
     2              NOSH,NPST(LPH),NHST(LPH),NPAIRD,L1R(8),ISR(8),
     3              ITR(8),NLSMAX,JT,KPARIT,IST,NOLTR,N1,LTR(8),
     4              ITP(LPH),ITH(LPH),ITZP(LPH),ITZH(LPH)	 
      COMMON/CGFAC /KAMAX,KGMAX,KCMAX,JLSMX,KBBSD(10),
     1              KBC(KCC),LAM2PC(KCC),LPP1C(KCC),LLP1D(KCC),
     2              NINTC(KCC),KDD(KGG),KCD(KGG),NLSD(KGG),LAMD(KAA),
     3              CLEBQ(KCC,5),CLEBF(KAA,5,5),COEF(KGG),CDDD(KJL) 
      COMMON/CGFAC2/JLSPMX,JLSCMX,KAD(KGG,5),NLTD(KJL),KKD(KJL),
     1              LAD(KJL),LBD(KJL),LYD(KJL),LTD(KJL),NND(KJL),
     2              CLEBD(KJL,10),CCDD(KJL,10) 
      COMMON/POTCC/ VA,VB,VX,VY,WA,WB,WX,WY ,WAS,WBS,WXS,WYS ,ARA,ARB,
     1              ARX,ARY,AIA,AIB,AIX,AIY,AISA,AISB,AISX,AISY,RZRA,
     2              RZRB,RZRX,RZRY,RZIA,RZIB,RZIX,RZIY,RZISA,RZISB,
     3              RZISX,RZISY,RZCA,RZCB,RZCX,RZCY,IDA,IDB,IDX,IDY,
     4              VRIT(900),NXMN,NXMX
      COMPLEX       VRIT
      COMMON/CXLM/  XLMRI(LTL,LM1,NXA),LLP1MX
      COMPLEX       XLMRI
      COMMON/CBST/  USAVP(NPS*NXA),USAVH(NHS*NXA),CY(LXA)
      COMPLEX       CY 
      COMMON/CCKF/  L1KFD(KFM),ISKFD(KFM),KKFD(KFM),LTKFD(KFM),KFMAX,
     1              ITKFD(KFM),NLSKFD(KFM),NLTKFD(KFM),LTMIM,LTMAX
      COMMON/DISW / DISWB(LXB*NXB),DISWA(LXA*NXA)
      COMPLEX       DISWA,DISWB
      COMPLEX       TTI,URI1         
CCCCC
CCCCC               DEFINE BASIC VARIABLES AND CONSTANTS
CCCCC
      KCT1=KCT
      LAP1MI=LDWMIR(1)+1
      LAP1MX=LDWMXR(1)+1
      LASTEP=LDWSTR(1)
      LBP1MI=LDWMIR(2)+1
      LBP1MX=LDWMXR(2)+1
      LBSTEP=LDWSTR(2)
      NOLA=(LAP1MX-LAP1MI)/LASTEP+1
      NOLB=(LBP1MX-LBP1MI)/LBSTEP+1
      LAM1MX=LAMMXD(1)+1
      LAM2MX=LAMMXD(2)+1
      LAMP1X=LAMMXD(3)+1
      L1MAX=L1R(NLSMAX)
      MP1MAX=LAMP1X
      LAM3MX=LAM1MX+LAM2MX-1
CCCCCC
      IF (KTLOUT(3).NE.0) THEN
      WRITE(8,825) LAM3MX,LAMP1X
  825 FORMAT(1H ,5X,'(GFAC)LAM3MX,LAMP1X=',4I3)
      ENDIF
      FPISQI=SQRT(1.0/(4.0*PI))
CCCCC
CCCCC                   CALCULATE G-FACTORS
CCCCC
      DO 10 I=1,KGG
      DO 10 J=1,5
   10 KAD(I,J)=0
      DO 11 I=1,KAA
      DO 11 J=1,5
      DO 11 K=1,5
   11 CLEBF(I,J,K)=0.
CCCCCC
      IF(KTLOUT(4).EQ.1) WRITE(8,830)
  830 FORMAT(//1H  ,'   KG  KC  KA  KB NLS LA1 LPP LA2  LL   K LT LAM',
     1              '    COEF    KA NLS    CLEBF')
      FAC1=PI*2.0
      L1RMX=L1R(NLSMAX)                       
      LLP1MX=L1RMX+LAMMXD(1)+1                
      IF(LLP1MX.GT.9) LLP1MX=9              
      KB=0
      KG=0
      KC=0
      KAMAX=1
      DO 120 NLS=1,NLSMAX
      L1=L1R(NLS)
      JJ=1
      DO 24 NLT=1,NOLTR
      LT=LTR(NLT)
      IF(L1.NE.LT) GO TO 24
      NLTM=NLT
      JJ=0
   24 CONTINUE
      IF(KCT1.EQ.1.AND.JJ.EQ.1)    GO TO 120
      L1TW=L1*2
      IS=ISR(NLS)
      IT=ITR(NLS)
      KB=KBBSD(NLS)
      LLL1=0
      DO 100 LAM1P1=1,LAM1MX
      LLL1=LLL1+1
      LAM1=LAM1P1-1
      LAM1TW=LAM1*2
      LPP=L1-LAM1-1
      NLPPMX=2*LAM1+1
      DO 98 NLPP=1,NLPPMX
      LPP=LPP+1
      IF(LPP.LT.0)    GO TO 98
      LPPTW=LPP*2
      KB=KB+1
      DO 96 LAM2P1=1,LAM2MX
      LAM2=LAM2P1-1
      LAM2TW=LAM2*2
      LL=LPP-LAM2-2
      DO 94  NLL=1,LAM2P1
      LL=LL+2
      IF (LL.LT.0)   GO TO 94
      IF (LL+1.GT.LLP1MX) GO TO 94               
      LLTW=LL*2
      KC=KC+1
      IF(KC.GT.KCC)  WRITE(8,840)
  840 FORMAT(1H  ,'KC  IS OVER KCC')
      KBC(KC)=KB
      LAM2PC(KC)=LAM2P1
      LPP1C(KC)=LPP+1
      NINTC(KC)=IT*3+IS+1
      H1=LLTW+1
      H2=LAM2TW+1
      HAT=SQRT(H1)/H2
      ID=0
      T1=1.0
      IA=LLTW
      IB=LPPTW
      IC=LAM2TW
      DO 50 M2=1,LAM2P1
      IE=(M2-1)*2
      IFF=IE
      CALL CLEB(IA,IB,IC,ID,IE,IFF,FACLOG,RAC) 
      CLEBQ(KC,M2)=RAC*FAC1*HAT*T1
      T1=2.0
   50 CONTINUE
CCCCC
      DO 86  LAMP1=1,LAMP1X
      LAM=LAMP1-1
      KAT=(LAMP1*LAM)/2+(LL+LAM-L1)/2+1
      IF(LAM.GT.(LL+L1).OR.LAM.LT.IABS(LL-L1)) GO TO 86
      IF(MOD(LL+LAM+KPARIT,2).NE.0)            GO TO 86
      KA=KAT
      IF(KA.GT.KAMAX) KAMAX=KA
      LAMTW=LAM*2
      KG=KG+1
      COEF(KG)=0.0
      KCD(KG)=KC
      KAD(KG,NLS)=KA
      NLTD(NLS)=NLTM
      LAMD(KA)=LAM
      IF(MOD(LAM1+LAM2+LAM,2).NE.0) GO TO 55
      IF(LAM.GT.(LAM1+LAM2).OR.LAM.LT.IABS(LAM1-LAM2)) GO TO 55
      IA=LAM1TW
      IB=LAM2TW
      IC=LAMTW
      CALL CLEBZ(IA,IB,IC,FACLOG,RAC) 
      C1=RAC
      H1=(LAM1TW+1)*(LAM2TW+1)
      C3=SQRT(H1)
      S1=1-MOD(LL,2)*2
      IA=LLTW
      IB=L1TW
      IC=LAM2TW
      ID=LAM1TW
      IE=LAMTW
      IFF=LPPTW
      CALL RAC7(IA,IB,IC,ID,IE,IFF,FACLOG,RAC) 
      C5=RAC
      A1=1.0
      COEF(KG)=COEF(KG)+C1*C3*C5*S1*FPISQI*A1
   55 CONTINUE
      ID=0
      IA=LLTW
      IB=LAMTW
      IC=L1TW
      H1=LLTW+1
      F1=FAC1*SQRT(H1)/FLOAT(L1TW+1)
      T1=1.0
      M1X=MIN0(L1MAX+1,LAMP1X)
      DO 60 M1=1,M1X
      IE=(M1-1)*2
      IFF=IE
      CALL CLEB(IA,IB,IC,ID,IE,IFF,FACLOG,RAC) 
      T2=1-2*MOD(M1-1,2)
      CLEBF(KA,M1,NLS)=RAC*F1*T1*T2
      T1=2.0
   60 CONTINUE
CCCCCC
      IF(KTLOUT(4).EQ.1) WRITE(8,850) KG,KC,KA,KBC(KC),
     1 NLS,LAM1,LPP,LAM2,LL,K,LT,LAM,COEF(KG),KA,NLTD(KA),
     1  ( CLEBF(KA,M1,NLS),M1=1,2),(CLEBQ(KC,M2),M2=1,LAM2MX)
   86 CONTINUE
   94 CONTINUE
   96 CONTINUE
   98 CONTINUE
  100 CONTINUE
  120 CONTINUE
      KCMAX=KC
      KGMAX=KG
CCCCCC
      WRITE(8,861) KGMAX,KCMAX,KAMAX
      IF(KGMAX.LE.KGG.AND.KCMAX.LE.KCC.AND.KAMAX.LE.KAA)
     1                GO TO 130
      WRITE(8,862)
      STOP
  130 CONTINUE
  850 FORMAT(1H  ,12I4,F8.3,I6,I4,2F8.3,3X,5F8.3)
  861 FORMAT(1H ,5X,'(GFAC)KGMAX,KCMAX,KAMAX=',3I3)
  862 FORMAT(1H ,'ONE OF KGMAX ETC IS OVER DIM. CALCULATION STOPS')
CCCCCC
      IE=0
      JLS=0
      LAM=0
      L1MAX=L1R(NLSMAX)
      MP1MAX=MIN0(L1MAX+1,LAMP1X)
      DO 300 LAP1=LAP1MI,LAP1MX,LASTEP
      LAM=LAM+1
      LA=LAP1-1
      LATW=LA*2
      IA=LATW
      DO 250 NLS=1,NLSMAX
      L1=L1R(NLS)
      IC=L1*2
      DO 244 LBP1=LBP1MI,LBP1MX
      LB=LBP1-1
      LBTW=LB*2
      H1=LBTW+1
      HAT=SQRT(H1)
      IF(LB.LT.IABS(LA-L1)) GO TO 244
      IF(LB.GT.LA+L1     )  GO TO 244
      MM1=1-2*MOD(LA+LB,2)
      MM2=1-2*MOD(KPARIT,2)
      IF(KCT.EQ.1.AND.MM1.NE.MM2) GO TO 244
      IB=LBTW
      JLS=JLS+1
      KK=(LAM-1)*NLSMAX+NLS
      KKD(JLS)=KK
      LAD(JLS)=LAM
      DO 242 M1=1,MP1MAX
      ID=(M1-1)*2
      IFF=ID
      CALL CLEB(IA,IB,IC,ID,IE,IFF,FACLOG,RAC) 
      CCDD(JLS,M1)=RAC*HAT
  242 CONTINUE
      IF(KTLOUT(4).EQ.1) WRITE(8,863) JLS,LA,LB,NLS,L1,KK,
     1        (CCDD(JLS,M1),M1=1,MP1MAX)
  244 CONTINUE
  250 CONTINUE
  300 CONTINUE
      JLSMX=JLS
  863 FORMAT(1H ,'JLS,LA,LB,NLS,L1,KK=',6I3,3F10.3)
CCCCCC
      IF (KTLOUT(3).NE.0) THEN
      WRITE(8,872) JLSMX,KCT
  872 FORMAT(1H ,5X,'(GFAC)JLSMX,KCT=',2(I8,2X))
      ENDIF
CCCCCC
      RETURN
      END


      SUBROUTINE TENSOR
CCCCCC
      PARAMETER(NHS=9,NPS=9,LXA=150,LXB=150,LPH=10,LMM=4,LTL=9)
      PARAMETER(NXA=420,NXB=140,NIN=300,NOU=300,N1X=140)
      PARAMETER(KFM=10,KAA=40,KBB=30,KCC=80,KGG=125,KJL=600,KTEN=5000)
      PARAMETER(LMJ=10,LRP=11,L1X=10,L2X=60,LM1=5,LM2=30,LAB=2000)
CCCCCC
      COMMON/CNST  /FACLOG(500),PI,HBAR,AMAS,WNUNIT,FINE
      COMMON/DWCC/  LDWMIR(4),LDWMXR(4),WN(4),LDWSTR(4),CE(4),CFUNIR(4),
     1              ECM(4),XMESR(4),NXMXR(4),NXMIR(4),NOEXP,MXSTEP,
     2              TMASA,TMASB,TMASX,TMASY,PMASA,PMASB,PMASX,PMASY,
     3              TZA,TZB,TZX,TZY,
     4              PZA,PZB,PZX,PZY,XBARD(4),XBARID(4),WNXD(20),EXPD(20)
      COMMON/CNTRL/ KTRLD(9),KTLOUT(24),NERUN,KRTYPE
      COMMON/FFCC/  VRANG(6),VSTR(12,6),VV(300,24),XMESH,XMESC,
     1              XMESHD,XMESHE,RHED(300),
     2              NBCMI,NBCMX,NONB,NBSTEP,LASTEP,LBSTEP,MAMAX,MXMAX,
     3              MP1MAX,NOLA,NOLB,INTRAN,LMI,LMX,KCETN(2),
     4              NCMAX,NCMIN,LDMAX,JATRTY,NONA,NONAH,NONAR,NASTEP,
     5              NHDMX,NHEMX,NGAUSR,NBSTPD,NBSTPE,N1STEP,JATW,ISATW
      COMMON/SPSTAT/EET,SPECTA(LPH),ESP(LPH),ESH(LPH),NSP(LPH),LSP(LPH),
     1              JTWP(LPH),NSH(LPH),LSH(LPH),JTWH(LPH),IPAIR,NOSP,
     2              NOSH,NPST(LPH),NHST(LPH),NPAIRD,L1R(8),ISR(8),
     3              ITR(8),NLSMAX,JT,KPARIT,IST,NOLTR,N1,LTR(8),
     4              ITP(LPH),ITH(LPH),ITZP(LPH),ITZH(LPH)
      COMMON/SPECFC/ALPHA(30,6)
      COMMON/CGFAC /KAMAX,KGMAX,KCMAX,JLSMX,KBBSD(10),
     1              KBC(KCC),LAM2PC(KCC),LPP1C(KCC),LLP1D(KCC),
     2              NINTC(KCC),KDD(KGG),KCD(KGG),NLSD(KGG),LAMDD(KAA),
     3              CLEBQ(KCC,5),CLEBF(KAA,5,5),COEF(KGG),CDDD(KJL) 
      COMMON/CGFAC2/JLSPMX,JLSCMX,KAD(KGG,5),NLTD(KJL),KKD(KJL),
     1              LAD(KJL),LBD(KJL),LYD(KJL),LTD(KJL),NND(KJL),
     2              CLEBD(KJL,10),CCDD(KJL,10) 
      COMMON/AMPL/  AMPD(700,8),AMPE(700,8)
      COMPLEX       AMPD,AMPE
      COMMON/DISW / DISWB(LXB*NXB),DISWA(LXA*NXA)
      COMPLEX       DISWB,DISWA
      DIMENSION     GGRIT(KJL),GGRITC(KJL),FFRIT(KJL)
      DIMENSION     C(KTEN),JLSD(KTEN),JLSPD(KTEN),LAMD(KTEN)
      DIMENSION     FFOUT(N1X,30),LAOUT(20)
      DIMENSION     L9(10)
      COMPLEX       FFRI,URI1,ZERO,TTI,GGRI,FFRIT,GGRIT,FFOUT,GGRITC
CCCCCC
      REWIND 13
      REWIND 14
      REWIND 15
CCCCCC
      LAP1MI=LDWMIR(1)+1
      LAP1MX=LDWMXR(1)+1
      LBP1MI=LDWMIR(2)+1
      LBP1MX=LDWMXR(2)+1
      LASTEP=LDWSTR(1)
      IF(LASTEP.EQ.0) LASTEP=1
      NOLA=(LAP1MX-LAP1MI)/LASTEP+1
      LAP1MX=LAP1MI+(NOLA-1)*LASTEP
      XMESA=XMESR(1)
      XMESB=XMESR(2)
      NMXA=NXMXR(1)
      NMIA=NXMIR(1)
      LTMAX=LTR(NOLTR)
      L1MAX=L1R(NLSMAX)
CCCCCC
      JLSPMX=JLSMX
      JLS=0
      KJLS=0
      DO 300 LAP1=LAP1MI,LAP1MX,LASTEP
      LA=LAP1-1
      LATW=LA*2
      DO 290 NLT=1,NOLTR
      LT=LTR(NLT)
      LTTW=LT*2
      LBM=0
      DO 280 LBP1=LBP1MI,LBP1MX
      LB=LBP1-1
      LBTW=LB*2
      IF(LB.LT.IABS(LA-LT))  GO TO 280
      IF(LB.GT.LA+LT      )  GO TO 280
      MM1=1-2*MOD(LA+LB,2)
      MM2=1-2*MOD(KPARIT,2)
      IF(MM1.NE.MM2) GO TO 280
      JLS=JLS+1
	LTD(JLS)=LT
	JLSC=0
      JLSP=0
      DO 270 LAPP1=LAP1MI,LAP1MX,LASTEP
      LAP=LAPP1-1
      LAPTW=LAP*2
      DO 268 NLS=1,NLSMAX
      L1=L1R(NLS)
      L1TW=L1*2
      DO 265 LBPP1=LBP1MI,LBP1MX
      LBP=LBPP1-1
      LBPTW=LBP*2
      IF(LBP.LT.IABS(LAP-L1)) GO TO 265
      IF(LBP.GT.LAP+L1      ) GO TO 265
      JLSP=JLSP+1
      MM1=1-2*MOD(LA+LB,2)
      MM2=1-2*MOD(KPARIT,2)
      IF(MM1.NE.MM2) GO TO 265
      JLSC=JLSC+1
      LYD(JLSC)=1
      IF(L1.EQ.LT) LYD(JLSC)=0
      DO 260 LAMAP1=1,3
      LAMA=LAMAP1-1
      LAMATW=LAMA*2
      LAMB=2-LAMA
      LAMBTW=LAMB*2
      IF(LAP.GT.(LA+LAMA).OR.LAP.LT.IABS(LA-LAMA)) GO TO 260
      IF(LBP.GT.(LB+LAMB).OR.LBP.LT.IABS(LB-LAMB)) GO TO 260
      IF(MOD(LA+LAMA+LAP,2).NE.0)                  GO TO 260
      IF(MOD(LB+LAMB+LBP,2).NE.0)                  GO TO 260
      KJLS=KJLS+1
      ID=0
      IE=0
      IF=0
      IA=LAPTW
      IB=LAMATW
      IC=LATW
      CALL CLEBZ(IA,IB,IC,FACLOG,RAC)  
      C1=RAC
      IA=LBPTW
      IB=LAMBTW
      IC=LBTW
      CALL CLEBZ(IA,IB,IC,FACLOG,RAC)  
      C2=RAC
      H1=(L1TW+1)*(LAPTW+1)*(LBPTW+1)*(LAMATW+1)*(LAMBTW+1)*5
      C3=SQRT(H1)
      L9(1)=LAPTW
      L9(2)=LAMATW
      L9(3)=LBPTW
      L9(4)=LAMBTW
      L9(5)=LATW
      L9(6)=LBTW
      L9(7)=L1TW
      L9(8)=4
      L9(9)=LTTW
      CALL NINEJ(L9,FACLOG,U9) 
      C4=U9
      T1=(FACLOG(6)-FACLOG(LAMATW+2)-FACLOG(LAMBTW+2))*0.5
      C5=EXP(T1)
      NLSK=NLSMAX+NLS
      A1=ALPHA(NLSK,NLT)
      FAC1=C1*C2*C3*C4*C5
      C(KJLS)=FAC1*A1
      JLSD(KJLS)=JLS
      JLSPD(KJLS)=JLSP
      LAMD(KJLS)=LAMA
  260 CONTINUE
  265 CONTINUE
  268 CONTINUE
  270 CONTINUE
  280 CONTINUE
  290 CONTINUE
  300 CONTINUE
      JLSMX=JLS
      KJLSMX=KJLS
	JLSEND=JLSMX-LTMAX*L1MAX
	JLSCEND=LTMAX*L1MAX
CCCCCC
CCCCCC
      IF (KTLOUT(3).NE.0) THEN
      WRITE(8,802) JLSPMX,JLSCMX,JLSMX,KJLSMX
  802 FORMAT(1H ,5X,'(TENSOR)JLSPMX,JLSCMX,JLSMX,KJLSMX=',10I6)
      ENDIF
CCCCCC
      NONAM=(NONA-1)/NASTEP+1
      DO 400 NBM=1,NONB
      NB=(NBM-1)*NBSTEP+NBCMI
      RB=XMESB*FLOAT(NB)
      NACENT=(RB+0.000001)/XMESA
      DO 380 NAM=1,NONAR 
      NA=(NAM-1)*NASTEP+NACENT-NONAH
      IF (NA.LE.0) GO TO 380
      IF(NA.LT.NMIA.OR.NA.GT.NMXA) GO TO 380
      DO 310 JLS=1,JLSMX
      GGRIT(JLS)=(0.0,0.0)
  310 CONTINUE
      IF(KCETN(2).EQ.1) GO TO 325
      READ  (14)  (FFRIT(JLSP),JLSP=1,JLSPMX)
      RA=XMESA*FLOAT(NA)
      DO 320 KJLS=1,KJLSMX
      JLS=JLSD(KJLS)
      JLSP=JLSPD(KJLS)
      LAMA=LAMD(KJLS)
      LAMB=2-LAMA
      SA=-PMASA
      C7=(SA*RA)**LAMA
      SB=PMASA
      C8=(SB*RB)**LAMB
      S1=1.0
      GGRIT(JLS)=GGRIT(JLS)+FFRIT(JLSP)*C(KJLS)*C7*C8*S1
	IF (JLS.GT.JLSEND) GGRIT(JLS)=(0.0,0.0)
  320 CONTINUE
CCCCCC
  325 CONTINUE
      DO 330 JLS=1,JLSMX
      GGRITC(JLS)=(0.0,0.0)
  330 CONTINUE
      IF(KCETN(1).EQ.1) GO TO 360
      READ (13) (FFRIT(JLS),JLS=1,JLSCMX)
CCCCCC
      DO 355 NLT=1,NOLTR
      LT=LTR(NLT)
	IF (NLT.EQ.1) THEN
      JLS=0
      JLSC=0
      DO 345 LAP1=LAP1MI,LAP1MX,LASTEP
      LA=LAP1-1
      DO 340 NLS=1,NLSMAX
      L1=L1R(NLS)
      DO 335 LBP1=LBP1MI,LBP1MX
      LB=LBP1-1
      IF(LB.LT.IABS(LA-L1))  GO TO 335
      IF(LB.GT.LA+L1      )  GO TO 335
      MM1=1-2*MOD(LA+LB,2)
      MM2=1-2*MOD(KPARIT,2)
      IF(MM1.NE. MM2) GO TO 335
      JLSC=JLSC+1
      IF (L1.NE.LT) GO TO 335
      JLS=JLS+1
      IF (NOLTR.EQ.1) GGRITC(JLS)=FFRIT(JLSC) 
      IF (NOLTR.GT.1.AND.JLSC.LE.JLSCEND) GGRITC(JLSC)=FFRIT(JLSC) 
  335 CONTINUE 
  340 CONTINUE
  345 CONTINUE
      ELSE
      JLS=0
      DO 350 JLSC=1,JLSCMX
      IF(LYD(JLSC).EQ.1) GO TO 350
      JLS=JLS+1
      GGRITC(JLSC)=GGRITC(JLSC)+FFRIT(JLSC)
  350 CONTINUE
      ENDIF
  355 CONTINUE
  360 DO 365 JLS=1,JLSMX
      GGRIT(JLS)=GGRIT(JLS)+GGRITC(JLS)
  365 CONTINUE
CCCCCC
      WRITE (15) (GGRIT(JLS),JLS=1,JLSMX)
      IF(KTLOUT(13).EQ.0) GO TO 375
      MEM1=0
      DO 370 JLS=1,JLSMX
      LA=LAD(JLS)
      KT13=KTLOUT(13)
      IF(MOD(LA,KT13).NE.0.OR.LA.GT.30) GO TO 370
      MEM1=MEM1+1
      FFOUT(NAM,MEM1)=GGRIT(JLS)
      LAOUT(MEM1)=LA
  370 CONTINUE
  375 CONTINUE
  380 CONTINUE
CCCCCC
      IF(KTLOUT(13).NE.0) THEN
      MEM1MX=MEM1
      DO 382 MEM2=1,MEM1MX
      WRITE(8,881) LAOUT(MEM2),NB,(FFOUT(NAM,MEM2),NAM=1,NONAM,10)
  382 CONTINUE
      ENDIF
  881 FORMAT(//1H ,'LA,NB=',2I3//(5X,12E10.3))
CCCCCC
  400 CONTINUE
CCCCCC
      RETURN
      END


      SUBROUTINE PACALE
CCCCCC
      PARAMETER(NHS=9,NPS=9,LXA=150,LXB=150,LPH=10,LMM=4,LTL=9)
      PARAMETER(NXA=420,NXB=140,NIN=300,NOU=300,N1X=140)
      PARAMETER(KFM=10,KAA=40,KBB=30,KCC=80,KGG=125,KJL=600,KTEN=5000)
      PARAMETER(LMJ=10,LRP=11,L1X=10,L2X=60,LM1=5,LM2=30,LAB=2000)
CCCCCC
      COMMON/CNST  /FACLOG(500),PI,HBAR,AMAS,WNUNIT,FINE
      COMMON/BSX/   URSAVE(500),ENEPT,VNEPT,VSOR,DFNR,DFNSO,RZR,RZSO,
     1              RZC,XMES2,Q,FTR,NODER,LBTR,JBTRTW,NXRAWF,KTRL4,
     2              KOPOT,LBTRY,JBTWY
      COMMON/DWCC/  LDWMIR(4),LDWMXR(4),WN(4),LDWSTR(4),CE(4),CFUNIR(4),
     1              ECM(4),XMESR(4),NXMXR(4),NXMIR(4),NOEXP,MXSTEP,
     2              TMASA,TMASB,TMASX,TMASY,PMASA,PMASB,PMASX,PMASY,
     3              TZA,TZB,TZX,TZY,
     4              PZA,PZB,PZX,PZY,XBARD(4),XBARID(4),WNXD(20),EXPD(20)
      COMMON/CNTRL/ KTRLD(9),KTLOUT(24),NERUN,KRTYPE
      COMMON/FFCC/  VRANG(6),VSTR(12,6),VV(300,24),XMESH,XMESC,
     1              XMESHD,XMESHE,RHED(300),
     2              NBCMI,NBCMX,NONB,NBSTEP,LASTEP,LBSTEP,MAMAX,MXMAX,
     3              MP1MAX,NOLA,NOLB,INTRAN,LMI,LMX,KCETN(2),
     4              NCMAX,NCMIN,LDMAX,JATRTY,NONA,NONAH,NONAR,NASTEP,
     5              NHDMX,NHEMX,NGAUSR,NBSTPD,NBSTPE,N1STEP,JATW,ISATW
      COMMON/CDENS/ RHOE(NXA,NIN,LMM),USAVEX(4*NXA),SPEC(4),
     1              DENSTY(NXA),LAMMXD(3),LBXD(4),NOSTX,NDMY
      COMMON/SPSTAT/EET,SPECTA(LPH),ESP(LPH),ESH(LPH),NSP(LPH),LSP(LPH),
     1              JTWP(LPH),NSH(LPH),LSH(LPH),JTWH(LPH),IPAIR,NOSP,
     2              NOSH,NPST(LPH),NHST(LPH),NPAIRD,L1R(8),ISR(8),
     3              ITR(8),NLSMAX,JT,KPARIT,IST,NOLTR,N1,LTR(8),
     4              ITP(LPH),ITH(LPH),ITZP(LPH),ITZH(LPH)
      COMMON/CGFAC /KAMAX,KGMAX,KCMAX,JLSMX,KBBSD(10),
     1              KBC(KCC),LAM2PC(KCC),LPP1C(KCC),LLP1D(KCC),
     2              NINTC(KCC),KDD(KGG),KCD(KGG),NLSD(KGG),LAMD(KAA),
     3              CLEBQ(KCC,5),CLEBF(KAA,5,5),COEF(KGG),CDDD(KJL) 
      COMMON/CGFAC2/JLSPMX,JLSCMX,KAD(KGG,5),NLTD(KJL),KKD(KJL),
     1              LAD(KJL),LBD(KJL),LYD(KJL),LTD(KJL),NND(KJL),
     2              CLEBD(KJL,10),CCDD(KJL,10) 
      COMMON/CGGR/  GGRIE(L1X,N1X)
      COMPLEX       GGRIE
      COMMON/ANGLC/ NTHEB,NOTHE,THEB,DTHEB
      COMMON/AMPL/  AMPD(700,8),AMPE(700,8)
      COMPLEX       AMPD,AMPE
      COMMON/OVDE/  OVDD(20,20),OVED(20,20),OVDDP(10,10),OVDEP(10,10)   
      COMPLEX       OVED,OVDD,OVDDP,OVDEP                               
      COMMON/DISW / DISWB(LXB*NXB),DISWA(LXA*NXA)
      COMPLEX       DISWB,DISWA
      DIMENSION     P(130,30),PP(130,10)
      DIMENSION     AF(500),AFI(500),XAF(500),XIAF(500),FSP(500),
     1              FSPI(500),Q1(500),AU(500)
      DIMENSION     FLA(10),FGR(10),FAN(10),FGE(10)
      DIMENSION     FFRIT(KJL),GGRI(4,NXA,KJL)
	DIMENSION     AMPEW(LXB,4,4)
      COMPLEX       FFRI,URI1,ZERO,TTI,GGRI,FFRIT,AMPEW
      DOUBLE PRECISION TT1,TTT1,TTH
CCCCCC
      REWIND 15
CCCCC
CCCCC             CALCULATION OF INTERPOLATION FACTORS
CCCCC
      NONAH1=NONAH+1
      FMC=NBSTEP
      DO 10 N=1,NBSTEP
      FN=N
      DELN=FN/FMC
      DELNM1=DELN-1.0
      DELNM2=DELN-2.0
      DELNP1=DELN+1.0
      FLA(N)=-DELN  *DELNM1*DELNM2/6.0
      FGR(N)= 0.5   *DELNP1*DELNM1*DELNM2
      FAN(N)=-0.5   *DELNP1*DELN  *DELNM2
      FGE(N)= DELNP1*DELN  *DELNM1/6.0
   10 CONTINUE
CCCCCC
      KFMAX=NOLTR
      KTRLH=0
      ZERO=(0.0,0.0)
      TTI=(0.0,1.0)
      IF(LDMAX.GT.14) LDMAX=14
      LAP1MI=LDWMIR(1)+1
      LAP1MX=LDWMXR(1)+1
      LBP1MI=LDWMIR(2)+1
      LBP1MX=LDWMXR(2)+1
      LASTEP=LDWSTR(1)
      IF (LASTEP.EQ.0) LASTEP=1
      NOLA=(LAP1MX-LAP1MI)/LASTEP+1
      LAP1MX=LAP1MI+(NOLA-1)*LASTEP
      SQ4PAI=SQRT(PI*4.0)
      NXMAX=NXMXR(1)
      NXMIN=NXMIR(1)
      NMXA=NXMXR(1)
      NMIA=NXMIR(1)
      NONAW=NXMAX-NXMIN+1
      NONBW=NXMXR(2)-NXMIR(2)+1
      NXMAX2=NXMAX+2
      NXMX=NXMAX2
      NXMN=1
      XMESA=XMESR(1)
      XMESB=XMESR(2)
      CONST=(SQ4PAI**3)/(WN(1)*WN(2))
      FJACOB=PMASA**3
      LTMAX=LTR(NOLTR)
      MP1MAX=MIN0(LTMAX+1,MXMAX+1)
      LBLTMX=NOLTR*NOLB-LTMAX
CCCCCC
      JLS=0
      LAMI=LAP1MI-1
      LBMI=LBP1MI-1
      ID=0
      LAMOUT=(NOLA+1)/2
      LTOUT=LTR(1)
      LAM=0
      DO 78 LAP1=LAP1MI,LAP1MX,LASTEP
      LA=LAP1-1
      LAM=LAM+1
      LATW=LA*2
      IA=LATW
      H1=LATW+1
      HAT=SQRT(H1)
      DO 77 NLT=1,NOLTR
      LT=LTR(NLT)
      LTP1=LT+1
      LTTW=LT*2
      IC=LTTW
      MP1MXT=MIN0(MP1MAX,LTP1)
      DO 75 LBP1=LBP1MI,LBP1MX
      LBM=LBP1-LBP1MI+1
      LB=LBP1-1
      IF(LB.LT.IABS(LA-LT)) GO TO 75
      IF(LB.GT.LA+LT      ) GO TO 75
      MM1=1-2*MOD(LA+LB,2)
      MM2=1-2*MOD(KPARIT,2)
      IF(MM1.NE.MM2)  GO TO 75
      JLS=JLS+1
      K1=IABS(LA-LB+KPARIT)/2
      S1=(-1.0)**K1
      IB=LB*2
      LAD(JLS)=(LAM-1)*NONAW
      LBD(JLS)=(LB-LBMI)*NONBW
      LTD(JLS)=LT
      NND(JLS)=(LB-LBMI)*NOLTR+NLT
      DO 70 M1=1,MP1MAX
   70 CLEBD(JLS,M1)=0.0
      DO 74 M1=1,MP1MXT
      IE=(M1-1)*2
      IFF=IE
      CALL CLEB(IA,IB,IC,ID,IE,IFF,FACLOG,RAC) 
      CLEBD(JLS,M1)=RAC*HAT*S1
   74 CONTINUE
   75 CONTINUE
   77 CONTINUE
   78 CONTINUE
CCCCC
      NONAT=(NONA-1)/NASTEP+1
      NONAM=NONAT
      DO 120 LBLT=1,LBLTMX
      DO 120 M1=1,MP1MAX
  120 AMPE(LBLT,M1)=(0.0,0.0)
      NMAX1=NONAM
      NGINT=NONA
      F1B=2.0
      NB=NBCMI+NBSTEP
      NBMI=NB+1
      N1=0
      NONBM=NONB-3
      NONBT=NBCMX-NBCMI+1
      XMESA3=XMESA/3.0
      XMESB3=XMESB/3.0
      XFAC3=XMESA3*XMESB3*CONST*FJACOB
      DO 300 NBM=1,NONBM
      IF(NBM.GT.1) GO TO 230
      DO 220 NBMT=1,4
      NBT=(NBMT-1)*NBSTEP+NBCMI
      RB=XMESB*FLOAT(NBT)
      NACENT=(RB+0.000001)/XMESA
      DO 203 NAMT=1,NONAR
      NA=(NAMT-1)*NASTEP+NACENT-NONAH
      IF(NA.LE.0) GO TO 203
      IF(NA.LT.NMIA.OR.NA.GT.NMXA) GO TO 203
      READ (15) (FFRIT(JLS),JLS=1,JLSMX)
      DO 202 JLS=1,JLSMX
      GGRI(NBMT,NAMT,JLS)=FFRIT(JLS)
  202 CONTINUE
  203 CONTINUE
  220 CONTINUE
      GO TO 250
  230 NBT=(NBM+2)*NBSTEP+NBCMI
      RB=XMESB*FLOAT(NBT)
      NACENT=(RB+0.000001)/XMESA
      DO 240 NAMT=1,NONAR
      NA=(NAMT-1)*NASTEP+NACENT-NONAH
      IF(NA.LE.0) GO TO 240
      IF(NA.LT.NMIA.OR.NA.GT.NMXA) GO TO 240
      READ (15) (FFRIT(JLS),JLS=1,JLSMX)
      DO 234 JLS=1,JLSMX
      GGRI(4,NAMT,JLS)=FFRIT(JLS)
  234 CONTINUE
  240 CONTINUE
  250 DO 290 I=1,NBSTEP
      NB=NB+1
      F1B=6.0-F1B
      FNB=NB
      RB=XMESB*FNB
      RBSQ=RB*RB
      NACENT=(RB+0.000001)/XMESA
      F1A=3.0
      DO 280 NAM=1,NONAR
      F1A=6.0-F1A
      NA=NAM+NACENT-NONAH-1
      IF(NA.LE.0) GO TO 280
      IF(NA.LT.NMIA.OR.NA.GT.NMXA) GO TO 280
      DO 270 JLS=1,JLSMX
      NB1=LBD(JLS)+NB
      NA1=LAD(JLS)+NA
      FFRI   =FLA(I)*GGRI(1,NAM,JLS)+FGR(I)*GGRI(2,NAM,JLS)
     1       +FAN(I)*GGRI(3,NAM,JLS)+FGE(I)*GGRI(4,NAM,JLS)
      C1=1.0
      T1=CABS(FFRI)
      T2=CABS(DISWA(NA1))
      T3=CABS(DISWB(NB1))
      IF(T1.LT.1.0E-20) GO TO 270
      IF(T2.LT.1.0E-20) GO TO 270
      IF(T3.LT.1.0E-20) GO TO 270
      URI1=FFRI*F1A*F1B*XFAC3*DISWA(NA1)*DISWB(NB1)
      LBLT=NND(JLS)
	IF (LBLT.GT.LBLTMX) GO TO 270
      DO 260 M1=1,MP1MAX
      C1=CLEBD(JLS,M1)
      AMPE(LBLT,M1)=AMPE(LBLT,M1)+URI1*C1
  260 CONTINUE
  270 CONTINUE
  280 CONTINUE
  290 CONTINUE
      DO 295 JLS=1,JLSMX
      DO 295 NAMT=1,NONAR
      DO 295 N1=2,4
      N2=N1-1
  295 GGRI(N2,NAMT,JLS)=GGRI(N1,NAMT,JLS)
  300 CONTINUE
CCCCCC
      IF (KTLOUT(3).NE.0) THEN
      LBLT=0
      DO 450 LBP1=LBP1MI,LBP1MX
	DO 440 NLT=1,NOLTR
        LBLT=LBLT+1
        DO 430 M1=1,MP1MAX
          AMPEW(LBP1,NLT,M1)=AMPE(LBLT,M1)
  430   CONTINUE 
  440 CONTINUE
  450 CONTINUE
      DO 480 M1=1,MP1MAX
	DO 470 NLT=1,NOLTR
	WRITE(8,809) NLT,M1
      WRITE(8,810) (AMPEW(LBP1,NLT,M1),LBP1=LBP1MI,LBP1MX)
  470 CONTINUE
  480 CONTINUE
      ENDIF
  809 FORMAT(/1H ,5X,'AMPE(LBP1,NLT,M1) AT NLT,M1=',2I3)
  810 FORMAT(1H ,5X,10E10.3)
CCCCC
CCCCC       SPHERICAL HARMONICS IN TRANSITION AMPLITUDE
CCCCCC
      TH=THEB*PI/180.0
      TTH=TH
      TT1=DCOS(TTH)
      CALL YLCAL(TT1,LBP1MX,MP1MAX,P)
CCCCC
      DO 510 NLT=1,NOLTR
      DO 510 M1=1,MP1MAX
      OVED(NLT,M1)=ZERO
  510 CONTINUE
CCCCCC  
      LBLT=0
      DO 550 LBP1=LBP1MI,LBP1MX
	DO 540 NLT=1,NOLTR
        LBLT=LBLT+1
        DO 530 M1=1,MP1MAX
          OVED(NLT,M1)=OVED(NLT,M1)+AMPE(LBLT,M1)*P(LBP1,M1)
  530   CONTINUE 
  540 CONTINUE
  550 CONTINUE
CCCCCC
      WRITE(8,851)
      DO 580 NLT=1,NOLTR                                                
        LT=LTR(NLT)                                                       
      WRITE(8,852) LT,(OVED(NLT,M1),M1=1,MP1MAX)                        
  580 CONTINUE
  851 FORMAT(/1H ,'EXCHANGE TRANSITION AMPLITUDES')
  852 FORMAT(1H ,'LT=',I2,10E10.3)
CCCCCC                        
      RETURN
      END
